name: Deploy OpenAPI Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Swagger UI
        run: |
          mkdir -p public
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v5.11.0.tar.gz
          tar -xzf v5.11.0.tar.gz --strip-components=1 -C public
          rm v5.11.0.tar.gz

      - name: Copy OpenAPI Spec
        run: |
          cp docs/openapi.yaml public/openapi.yaml

      - name: Configure Swagger UI to Use Your OpenAPI Spec
        run: |
          echo 'window.ui = SwaggerUIBundle({url: "./openapi.yaml", dom_id: "#swagger-ui"});' > public/swagger-initializer.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public
